crab -create -cfg TMB_Baseline_1.cfg
crab -create -cfg clctToAlct.cfg
crab -create -cfg SLHC.cfg
crab -create -cfg alctGhostCancellationSideQuality.cfg
crab -create -cfg alctNarrowMaskForR1.cfg
crab -create -cfg alctPretrigDeadtime.cfg
crab -create -cfg alctGhostCancellationBxDepth.cfg
crab -create -cfg useDeadTimeZoning.cfg
crab -create -cfg useDynamicStateMachineZone.cfg
crab -create -cfg clctPidThreshPretrig.cfg
crab -create -cfg clctMinSeparation.cfg
crab -create -cfg TMB_Baseline_2.cfg
crab -create -cfg matchTrigWindowSize.cfg
crab -create -cfg alctUseCorrectedBx.cfg
crab -create -cfg clctUseCorrectedBx.cfg
crab -create -cfg tmbDropUsedClcts_matchEarliestClctME11Only.cfg
crab -create -cfg tmbCrossBxAlgorithm.cfg
crab -create -cfg tmbReadoutEarliest2.cfg
