crab -get -c TMB_Baseline_1
crab -get -c clctToAlct
crab -get -c SLHC
crab -get -c alctGhostCancellationSideQuality
crab -get -c alctNarrowMaskForR1
crab -get -c alctPretrigDeadtime
crab -get -c alctGhostCancellationBxDepth
crab -get -c useDeadTimeZoning
crab -get -c useDynamicStateMachineZone
crab -get -c clctPidThreshPretrig
crab -get -c clctMinSeparation
crab -get -c TMB_Baseline_2
crab -get -c matchTrigWindowSize
crab -get -c alctUseCorrectedBx
crab -get -c clctUseCorrectedBx
crab -get -c tmbDropUsedClcts_matchEarliestClctME11Only
crab -get -c tmbCrossBxAlgorithm
crab -get -c tmbReadoutEarliest2
