crab -status -c TMB_Baseline_1
crab -status -c clctToAlct
crab -status -c SLHC
crab -status -c alctGhostCancellationSideQuality
crab -status -c alctNarrowMaskForR1
crab -status -c alctPretrigDeadtime
crab -status -c alctGhostCancellationBxDepth
crab -status -c useDeadTimeZoning
crab -status -c useDynamicStateMachineZone
crab -status -c clctPidThreshPretrig
crab -status -c clctMinSeparation
crab -status -c TMB_Baseline_2
crab -status -c matchTrigWindowSize
crab -status -c alctUseCorrectedBx
crab -status -c clctUseCorrectedBx
crab -status -c tmbDropUsedClcts_matchEarliestClctME11Only
crab -status -c tmbCrossBxAlgorithm
crab -status -c tmbReadoutEarliest2
