crab -submit -c TMB_Baseline_1
crab -submit -c clctToAlct
crab -submit -c SLHC
crab -submit -c alctGhostCancellationSideQuality
crab -submit -c alctNarrowMaskForR1
crab -submit -c alctPretrigDeadtime
crab -submit -c alctGhostCancellationBxDepth
crab -submit -c useDeadTimeZoning
crab -submit -c useDynamicStateMachineZone
crab -submit -c clctPidThreshPretrig
crab -submit -c clctMinSeparation
crab -submit -c TMB_Baseline_2
crab -submit -c matchTrigWindowSize
crab -submit -c alctUseCorrectedBx
crab -submit -c clctUseCorrectedBx
crab -submit -c tmbDropUsedClcts_matchEarliestClctME11Only
crab -submit -c tmbCrossBxAlgorithm
crab -submit -c tmbReadoutEarliest2
